import type { Snapshot } from './types';

export const sampleSnapshot: Snapshot = {
  spreadsheetName: 'Sample',
  spreadsheetUrl: '',
  events: [
    {
      id: 'evt_reno',
      name: 'House renovation',
      note: 'Living room and study',
      budget: 200000,
      createdAt: '2026-09-01T08:00:00.000Z',
      archived: false,
    },
    {
      id: 'evt_goa',
      name: 'Goa trip',
      note: 'Long weekend',
      budget: 40000,
      createdAt: '2026-09-10T08:00:00.000Z',
      archived: false,
    },
  ],
  categories: [
    { id: 'cat_food', name: 'Food', archived: false },
    { id: 'cat_stay', name: 'Stay', archived: false },
    { id: 'cat_travel', name: 'Travel', archived: false },
    { id: 'cat_transport', name: 'Transport', archived: false },
    { id: 'cat_decor', name: 'Decor', archived: false },
    { id: 'cat_maint', name: 'Maintenance', archived: false },
    { id: 'cat_furniture', name: 'Furniture', archived: false },
    { id: 'cat_shopping', name: 'Shopping', archived: false },
    { id: 'cat_utilities', name: 'Utilities', archived: false },
    { id: 'cat_medical', name: 'Medical', archived: false },
    { id: 'cat_other', name: 'Other', archived: false },
  ],
  expenses: [
    {
      id: 'ex_flight',
      eventId: 'evt_goa',
      categoryId: 'cat_travel',
      title: 'Flights',
      note: '',
      amount: 14500,
      date: '2026-09-12',
      createdAt: '2026-09-12T09:00:00.000Z',
    },
    {
      id: 'ex_hotel',
      eventId: 'evt_goa',
      categoryId: 'cat_stay',
      title: 'Hotel',
      note: 'Two nights',
      amount: 8200,
      date: '2026-09-12',
      createdAt: '2026-09-12T18:00:00.000Z',
    },
    {
      id: 'ex_cab',
      eventId: 'evt_goa',
      categoryId: 'cat_transport',
      title: 'Airport cab',
      note: '',
      amount: 900,
      date: '2026-09-12',
      createdAt: '2026-09-12T20:00:00.000Z',
    },
    {
      id: 'ex_dinner',
      eventId: 'evt_goa',
      categoryId: 'cat_food',
      title: 'Dinner',
      note: 'Fish thali',
      amount: 1800,
      date: '2026-09-13',
      createdAt: '2026-09-13T21:00:00.000Z',
    },
    {
      id: 'ex_chair',
      eventId: 'evt_reno',
      categoryId: 'cat_furniture',
      title: 'Study chair',
      note: 'From the studio',
      amount: 8900,
      date: '2026-09-18',
      createdAt: '2026-09-18T11:00:00.000Z',
    },
    {
      id: 'ex_lights',
      eventId: 'evt_reno',
      categoryId: 'cat_decor',
      title: 'Ceiling lights',
      note: '',
      amount: 3400,
      date: '2026-10-01',
      createdAt: '2026-10-01T10:00:00.000Z',
    },
    {
      id: 'ex_paint',
      eventId: 'evt_reno',
      categoryId: 'cat_maint',
      title: 'Paint and labour',
      note: '',
      amount: 12500,
      date: '2026-10-02',
      createdAt: '2026-10-02T16:00:00.000Z',
    },
    {
      id: 'ex_souvenir',
      eventId: 'evt_goa',
      categoryId: 'cat_shopping',
      title: 'Souvenirs',
      note: '',
      amount: 650,
      date: '2026-10-03',
      createdAt: '2026-10-03T08:00:00.000Z',
    },
  ],
};
